shinyproxy:
  apps:
    - id: 02_opendata_enr
      display-name: EnR
      description: Shiny app without restricted access (EnR)
      container-image: blenzi/enr
      container-cmd: ["R", "-e", "shiny::runApp('app')"]
      access-groups: []

  proxyConfig:
    authentication:
      type: none

  ingress:
    enabled: true
    hostname: enr.lab.sspcloud.fr
