shiny:
  image:
    repository: blenzi/enr-app
    pullPolicy: Always
    tag: master
  ingress:
    enabled: true
    hostname: enr.lab.sspcloud.fr
  s3:
    enabled: true
    existingSecret: app-s3
  postgresql:
    enabled: false
    auth:
      username: myusername
      database: defaultdb
      existingSecret: myshinyapp-postgresql
    containerPorts:
      postgresql: 5432
    fullnameOverride: postgresql-db
    primary:
      persistence:
        size: 2Gi
  