shiny:
  image:
    repository: blenzi/enr-app
    pullPolicy: Always
    tag: master
  ingress:
    enabled: true
    hostname: enr.lab.sspcloud.fr
  probe:
    enabled: true
    probeValue:
        livenessProbe:
          timeoutSeconds: 30
        readinessProbe:
          timeoutSeconds: 30
        startupProbe:
          timeoutSeconds: 100
          periodSeconds: 30
  resources:
    requests:
      cpu: "0.5"
  s3:
    enabled: true
    existingSecret: enr-s3
