shiny:
  image:
    repository: blenzi/enr-shiny
    tag: v1
  ingress:
    enabled: true
    hostname: enr-shiny.lab.sspcloud.fr
  probe:
    enabled: true
  probeValue:
      livenessProbe:
        timeoutSeconds: 30
      readinessProbe:
        timeoutSeconds: 30
      startupProbe:
        timeoutSeconds: 100
        periodSeconds: 100
  s3:
    enabled: true
    existingSecret: app-s3
  