shiny:
  image:
    repository: blenzi/enr-shiny
    tag: v1.1
  ingress:
    enabled: true
    hostname: enr-shiny.lab.sspcloud.fr
  probe:
    enabled: true
    probeValue:
        livenessProbe:
          timeoutSeconds: 30
        readinessProbe:
          timeoutSeconds: 30
        startupProbe:
          timeoutSeconds: 100
          periodSeconds: 200
  resources:
    requests:
      cpu: "0.5"
  s3:
    enabled: true
    existingSecret: enr-s3
